<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>

        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <link href="${pageContext.request.contextPath}/libs/img/Diamond-icon.png" rel="shortcut icon" >
        <title>Jewelry</title>

        <!-- Bootstrap Core CSS -->
        <link type="text/css" href="${pageContext.request.contextPath}/libs/css/bootstrap.css" rel="stylesheet" >
        <!-- Theme CSS -->
        <link type="text/css" href="${pageContext.request.contextPath}/libs/css/style.css" rel="stylesheet" >

        <!-- Custom Fonts -->
        <link type="text/css" href="${pageContext.request.contextPath}/libs/fonts/css/font-awesome.min.css" rel="stylesheet" >
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

        <!-- jQuery -->
        <script type="text/javascript" src="${pageContext.request.contextPath}/libs/js/jssor.js"></script>
        <script type="text/javascript" src="${pageContext.request.contextPath}/libs/js/jquery.min.js"></script>

        <!-- Bootstrap Core JavaScript -->
        <script type="text/javascript" src="${pageContext.request.contextPath}/libs/js/bootstrap.min.js"></script>

        <!-- Plugin JavaScript -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>

        <!-- Contact Form JavaScript -->
        <script type="text/javascript" src="${pageContext.request.contextPath}/libs/js/jqBootstrapValidation.js"></script>

        <!-- Theme JavaScript -->
        <script type="text/javascript" src="${pageContext.request.contextPath}/libs/js/freelancer.min.js"></script>

    </head>
    <body id="page-top" class="index">

        <!-- Thương hiệu -->
        <section class="success" id="thuonghieu">
            <div class="container-fluid" style="padding:0px; margin:0px;margin-bottom:10px;">
                <div class="row">
                    <div class="col-lg-12 text-center">
                        <h2>THƯƠNG HIỆU</h2>
                        <hr class="star-light">
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12 jssor">
                        <!-- #region Jssor Slider Begin -->
                        <!-- Generated by Jssor Slider Maker Online. -->
                        <!-- This is deep minimized demo, it works alone, it doesn't depend on any javascript library. -->
                        <div id="jssor_1" style="position: relative; margin: 0 auto; top: 0px; left: 0px; width: 1300px;
                             height: 500px; overflow: hidden; visibility: hidden;">
                            <!-- Loading Screen -->
                            <div data-u="loading" style="position: absolute; top: 0px; left: 0px;">
                                <div style="filter: alpha(opacity=70); opacity: 0.7; position: absolute; display: block; top: 0px;
                                     left: 0px; width: 100%; height: 100%;"></div>
                                <div style="position:absolute;display:block;background:url('img/loading.gif') no-repeat center center;
                                     top:0px;left:0px;width:100%;height:100%;"></div>
                            </div>
                            <div data-u="slides" style="cursor: default; position: relative; top: 0px; left: 0px; width: 1300px;
                                 height: 500px; overflow: hidden;">
                                <div data-p="225.00" style="display: none;">
                                    <img data-u="image" src="${pageContext.request.contextPath}/libs/img/Jemma.png" />
                                    <div style="position: absolute; top: 40px; left: 950px; width: 480px; height: 120px; font-size: 50px;
                                         color: #ffffff; line-height: 60px;"><img src="${pageContext.request.contextPath}/libs/img/JEMMA4.png">
                                    </div>
                                    <div style="position: absolute; top: 100px; left: 30px; width: 480px; height: 120px; font-size: 20px;
                                         color: #ffffff; line-height: 30px;">
                                        Trang sức Jemma với những sản phẩm nữ trang và phụ kiện thời trang hiện đại, phá cách, mang lại dấu ấn của sự thanh lịch, quý phái cho người sở hữu.
                                    </div>
                                </div>
                                <div data-p="225.00" style="display: none;">
                                    <img data-u="image" src="${pageContext.request.contextPath}/libs/img/PNJ_GOLD.png" />
                                    <div style="position: absolute; top: 40px; left: 950px; width: 480px; height: 120px; font-size: 50px;
                                         color: #ffffff; line-height: 60px;"><img src="${pageContext.request.contextPath}/libs/img/PNJ3.png">
                                    </div>
                                    <div style="position: absolute; top: 100px; left: 30px; width: 480px; height: 120px; font-size: 20px;
                                         color: #ffffff; line-height: 30px;">
                                        Trang sức Vàng PNJ luôn khẳng định vị trí dẫn đầu trong ngành kim hoàn và thời trang với những sản phẩm trang sức tinh tế, chất lượng vượt trội, góp phần tôn vinh vẻ đẹp, giá trị đích thực của người sở hữu.
                                    </div>
                                </div>
                                <div data-p="225.00" style="display: none;">
                                    <img data-u="image" src="${pageContext.request.contextPath}/libs/img/Silver.png" />
                                    <div style="position: absolute; top: 40px; left: 950px; width: 480px; height: 120px; font-size: 50px; 
                                         color: #ffffff; line-height: 60px;"><img src="${pageContext.request.contextPath}/libs/img/Silver4.png">
                                    </div>
                                    <div style="position: absolute; top: 100px; left: 30px; width: 480px; height: 120px; font-size: 20px;
                                         color: #a9188d; line-height: 30px;">
                                        Trang sức bạc và phụ kiện thời trang PNJSilver được chọn lựa bởi những tín đồ yêu thích vẻ đẹp độc đáo, khẳng định phong cách riêng và tự tin tỏa sáng.
                                    </div>
                                </div>
                                <div data-p="225.00" style="display: none;">
                                    <img data-u="image" src="${pageContext.request.contextPath}/libs/img/CAO.jpg" />
                                    <div style="position: absolute; top: 40px; left: 950px; width: 480px; height: 120px; font-size: 50px;
                                         color: #ffffff; line-height: 60px;"><img src="${pageContext.request.contextPath}/libs/img/CAO3.png">
                                    </div>
                                    <div style="position: absolute; top: 100px; left: 30px; width: 480px; height: 120px; font-size: 20px;
                                         color: #ffffff; line-height: 30px;">
                                        CAO Fine Jewellery là nhãn hiệu trang sức cao cấp hàng đầu, đột phá trong thiết kế, áp dụng kỹ thuật công nghệ cao với tay nghề chế tác tinh xảo, sẵn sàng chinh phục những tín đồ thời trang đẳng cấp.
                                    </div>
                                </div>
                            </div>
                            <!-- Bullet Navigator -->
                            <div data-u="navigator" class="jssorb05" style="bottom:16px;right:16px;" data-autocenter="1">
                                <!-- bullet navigator item prototype -->
                                <div data-u="prototype" style="width:16px;height:16px;"></div>
                            </div>
                            <!-- Arrow Navigator -->
                            <span data-u="arrowleft" class="jssora22l" style="top:0px;left:12px;width:40px;height:58px;" data-autocenter="2"></span>
                            <span data-u="arrowright" class="jssora22r" style="top:0px;right:12px;width:40px;height:58px;" data-autocenter="2"></span>
                            <a href="http://www.jssor.com" style="display:none">Bootstrap Carousel</a>
                        </div>
                        <script>
                            jssor_1_slider_init();
                        </script>
                        <!-- #endregion Jssor Slider End -->
                    </div>
                </div>
            </div>
        </section>

        <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
        <div class="scroll-top page-scroll hidden-sm hidden-xs hidden-lg hidden-md">
            <a class="btn btn-primary" href="#page-top">
                <i class="fa fa-chevron-up"></i>
            </a>
        </div>

    </body>
</html>
