
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <jsp:include page="menu.jsp" />
    </head>
    <body id="page-top" class="index">

        <!-- Loại trang sức -->
        <section id="loaitrangsuc">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 text-center">
                        <h2>Loại trang sức</h2>
                        <hr class="star-primary">
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4 loaitrangsuc-item" >
                        <a href="loaitrangsuc.html" class="loaitrangsuc-link">
                            <div class="caption">
                                <div class="caption-content">
                                    <i class="fa fa-search-plus fa-3x"></i>
                                </div>
                            </div>
                            <img src="img/trangsuckimcuong.jpg" class="img-responsive loaitrangsuc" alt="">
                        </a>
                    </div>
                    <div class="col-sm-4 loaitrangsuc-item">
                        <a href="loaitrangsuc.html" class="loaitrangsuc-link">
                            <div class="caption">
                                <div class="caption-content">
                                    <i class="fa fa-search-plus fa-3x"></i>
                                </div>
                            </div>
                            <img src="img/trangsuckimcuong.jpg" class="img-responsive loaitrangsuc" alt="">
                        </a>
                    </div>
                    <div class="col-sm-4 loaitrangsuc-item">
                        <a href="loaitrangsuc.html" class="loaitrangsuc-link">
                            <div class="caption">
                                <div class="caption-content">
                                    <i class="fa fa-search-plus fa-3x"></i>
                                </div>
                            </div>
                            <img src="img/trangsuckimcuong.jpg" class="img-responsive loaitrangsuc" alt="">
                        </a>
                    </div>
                    <div class="col-sm-4 loaitrangsuc-item">
                        <a href="loaitrangsuc.html" class="loaitrangsuc-link">
                            <div class="caption">
                                <div class="caption-content">
                                    <i class="fa fa-search-plus fa-3x"></i>
                                </div>
                            </div>
                            <img src="img/trangsuckimcuong.jpg" class="img-responsive loaitrangsuc" alt="">
                        </a>
                    </div>
                    <div class="col-sm-4 loaitrangsuc-item">
                        <a href="loaitrangsuc.html" class="loaitrangsuc-link">
                            <div class="caption">
                                <div class="caption-content">
                                    <i class="fa fa-search-plus fa-3x"></i>
                                </div>
                            </div>
                            <img src="img/trangsuckimcuong.jpg" class="img-responsive loaitrangsuc" alt="">
                        </a>
                    </div>
                    <div class="col-sm-4 loaitrangsuc-item">
                        <a href="loaitrangsuc.html" class="loaitrangsuc-link">
                            <div class="caption">
                                <div class="caption-content">
                                    <i class="fa fa-search-plus fa-3x"></i>
                                </div>
                            </div>
                            <img src="img/trangsuckimcuong.jpg" class="img-responsive loaitrangsuc" alt="">
                        </a>
                    </div>
                </div>
            </div>
        </section>

        <!-- Thương hiệu -->
        <section class="success" id="thuonghieu">
            <div class="container-fluid" style="padding:0px; margin:0px;margin-bottom:10px;">
                <div class="row">
                    <div class="col-lg-12 text-center">
                        <h2>THƯƠNG HIỆU</h2>
                        <hr class="star-light">
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12 jssor">
                        <!-- #region Jssor Slider Begin -->
                        <!-- Generated by Jssor Slider Maker Online. -->
                        <!-- This is deep minimized demo, it works alone, it doesn't depend on any javascript library. -->
                        <div id="jssor_1" style="position: relative; margin: 0 auto; top: 0px; left: 0px; width: 1300px;
                             height: 500px; overflow: hidden; visibility: hidden;">
                            <!-- Loading Screen -->
                            <div data-u="loading" style="position: absolute; top: 0px; left: 0px;">
                                <div style="filter: alpha(opacity=70); opacity: 0.7; position: absolute; display: block; top: 0px;
                                     left: 0px; width: 100%; height: 100%;"></div>
                                <div style="position:absolute;display:block;background:url('img/loading.gif') no-repeat center center;
                                     top:0px;left:0px;width:100%;height:100%;"></div>
                            </div>
                            <div data-u="slides" style="cursor: default; position: relative; top: 0px; left: 0px; width: 1300px;
                                 height: 500px; overflow: hidden;">
                                <div data-p="225.00" style="display: none;">
                                    <img data-u="image" src="img/Jemma.png" />
                                    <div style="position: absolute; top: 40px; left: 950px; width: 480px; height: 120px; font-size: 50px;
                                         color: #ffffff; line-height: 60px;"><img src="img/JEMMA4.png">
                                    </div>
                                    <div style="position: absolute; top: 100px; left: 30px; width: 480px; height: 120px; font-size: 20px;
                                         color: #ffffff; line-height: 30px;">
                                        Trang sức Jemma với những sản phẩm nữ trang và phụ kiện thời trang hiện đại, phá cách, mang lại dấu ấn của sự thanh lịch, quý phái cho người sở hữu.
                                    </div>
                                </div>
                                <div data-p="225.00" style="display: none;">
                                    <img data-u="image" src="img/PNJ_GOLD.png" />
                                    <div style="position: absolute; top: 40px; left: 950px; width: 480px; height: 120px; font-size: 50px;
                                         color: #ffffff; line-height: 60px;"><img src="img/PNJ3.png">
                                    </div>
                                    <div style="position: absolute; top: 100px; left: 30px; width: 480px; height: 120px; font-size: 20px;
                                         color: #ffffff; line-height: 30px;">
                                        Trang sức Vàng PNJ luôn khẳng định vị trí dẫn đầu trong ngành kim hoàn và thời trang với những sản phẩm trang sức tinh tế, chất lượng vượt trội, góp phần tôn vinh vẻ đẹp, giá trị đích thực của người sở hữu.
                                    </div>
                                </div>
                                <div data-p="225.00" style="display: none;">
                                    <img data-u="image" src="img/Silver.png" />
                                    <div style="position: absolute; top: 40px; left: 950px; width: 480px; height: 120px; font-size: 50px; 
                                         color: #ffffff; line-height: 60px;"><img src="img/Silver4.png">
                                    </div>
                                    <div style="position: absolute; top: 100px; left: 30px; width: 480px; height: 120px; font-size: 20px;
                                         color: #a9188d; line-height: 30px;">
                                        Trang sức bạc và phụ kiện thời trang PNJSilver được chọn lựa bởi những tín đồ yêu thích vẻ đẹp độc đáo, khẳng định phong cách riêng và tự tin tỏa sáng.
                                    </div>
                                </div>
                                <div data-p="225.00" style="display: none;">
                                    <img data-u="image" src="img/CAO.jpg" />
                                    <div style="position: absolute; top: 40px; left: 950px; width: 480px; height: 120px; font-size: 50px;
                                         color: #ffffff; line-height: 60px;"><img src="img/CAO3.png">
                                    </div>
                                    <div style="position: absolute; top: 100px; left: 30px; width: 480px; height: 120px; font-size: 20px;
                                         color: #ffffff; line-height: 30px;">
                                        CAO Fine Jewellery là nhãn hiệu trang sức cao cấp hàng đầu, đột phá trong thiết kế, áp dụng kỹ thuật công nghệ cao với tay nghề chế tác tinh xảo, sẵn sàng chinh phục những tín đồ thời trang đẳng cấp.
                                    </div>
                                </div>
                            </div>
                            <!-- Bullet Navigator -->
                            <div data-u="navigator" class="jssorb05" style="bottom:16px;right:16px;" data-autocenter="1">
                                <!-- bullet navigator item prototype -->
                                <div data-u="prototype" style="width:16px;height:16px;"></div>
                            </div>
                            <!-- Arrow Navigator -->
                            <span data-u="arrowleft" class="jssora22l" style="top:0px;left:12px;width:40px;height:58px;" data-autocenter="2"></span>
                            <span data-u="arrowright" class="jssora22r" style="top:0px;right:12px;width:40px;height:58px;" data-autocenter="2"></span>
                            <a href="http://www.jssor.com" style="display:none">Bootstrap Carousel</a>
                        </div>
                        <script>
                            jssor_1_slider_init();
                        </script>
                        <!-- #endregion Jssor Slider End -->
                    </div>
                </div>
            </div>
        </section>

        <!-- Footer -->
        <footer class="text-center">
            <div class="footer-above">
                <div class="container">
                    <div class="row">
                        <div class="footer-col col-md-4">
                            <h3>Location</h3>
                            <p>3481 Melrose Place
                                <br>Beverly Hills, CA 90210</p>
                        </div>
                        <div class="footer-col col-md-4">
                            <h3>Around the Web</h3>
                            <ul class="list-inline">
                                <li>
                                    <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-facebook"></i></a>
                                </li>
                                <li>
                                    <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-google-plus"></i></a>
                                </li>
                                <li>
                                    <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-twitter"></i></a>
                                </li>
                                <li>
                                    <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-linkedin"></i></a>
                                </li>
                                <li>
                                    <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-dribbble"></i></a>
                                </li>
                            </ul>
                        </div>
                        <div class="footer-col col-md-4">
                            <h3>About Freelancer</h3>
                            <p>Freelance is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="footer-below">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            Copyright &copy; Your Website 2016
                        </div>
                    </div>
                </div>
            </div>
        </footer>

        <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
        <div class="scroll-top page-scroll hidden-sm hidden-xs hidden-lg hidden-md">
            <a class="btn btn-primary" href="#page-top">
                <i class="fa fa-chevron-up"></i>
            </a>
        </div>

        <!-- Đăng ký -->
        <div class="portfolio-modal modal fade" id="dangky" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-content">
                <div class="close-modal" data-dismiss="modal">
                    <div class="lr">
                        <div class="rl">
                        </div>
                    </div>
                </div>
                <div class="container">
                    <div class="row">
                        <div class="col-lg-8 col-lg-offset-2">
                            <div class="modal-body">
                                <h2>ĐĂNG KÝ</h2>
                                <hr class="star-primary">
                                <div class="form">
                                    <form class="form-group form-validate form-horizontal" id="register-form" method="get" action="">
                                        <div class="form-group">
                                            <label for="ten" class="control-label col-lg-3">Họ và tên <span class="required">*</span></label>
                                            <div class="col-lg-9">
                                                <input class=" form-control" id="ten" name="ten" type="text" placeholder="Họ tên"/>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label for="ngaysinh" class="control-label col-lg-3">Ngày sinh <span class="required">*</span></label>
                                            <div class="col-lg-9">
                                                <input class=" form-control" id="ngaysinh" name="ngaysinh" type="date" />
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label col-lg-3">Giới tính <span class="required">*</span></label>
                                            <div class="col-lg-9">                               
                                                <select class="form-control" id="gioitinh" name="gioitinh">
                                                    <option value="">--- Chọn giới tính ---</option>
                                                    <option value="1">Nam</option>
                                                    <option value="2">Nữ</option>
                                                </select>  
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="diachi" class="control-label col-lg-3">Địa chỉ <span class="required">*</span></label>
                                            <div class="col-lg-9">
                                                <textarea class="form-control" id="diachi" name="diachi" placeholder="Địa chỉ"></textarea>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="sodienthoai" class="control-label col-lg-3">Số điện thoại <span class="required">*</span></label>
                                            <div class="col-lg-9">
                                                <input class=" form-control" id="sodienthoai" name="sodienthoai" type="text" placeholder="Số điện thoại"/>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="ten" class="control-label col-lg-3">Email <span class="required">*</span></label>
                                            <div class="col-lg-9">
                                                <input class=" form-control" id="ten" name="ten" type="text" placeholder="Họ tên"/>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="tendangnhap" class="control-label col-lg-3">Tên đăng nhập <span class="required">*</span></label>
                                            <div class="col-lg-9">
                                                <input class="form-control " id="tendangnhap" name="tendangnhap" type="text" placeholder="Tên đăng nhập"/>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="matkhau" class="control-label col-lg-3">Mật khẩu <span class="required">*</span></label>
                                            <div class="col-lg-9">
                                                <input class="form-control " id="matkhau" name="matkhau" type="password" placeholder="Mật khẩu"/>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="confirm_password" class="control-label col-lg-3">Nhập lại mật khẩu <span class="required">*</span></label>
                                            <div class="col-lg-9">
                                                <input class="form-control " id="confirm_password" name="confirm_password" type="password" placeholder="Nhập lại mật khẩu"/>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-lg-offset-2 col-lg-10">
                                                <button class="btn btn-success" type="submit">Đăng ký</button>
                                                <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fa fa-times"></i> Đóng
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Đăng ký end -->


</body>
</html>
