package entity;
// Generated Dec 23, 2016 5:22:55 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Chitietdonhang generated by hbm2java
 */
@Entity
@Table(name="chitietdonhang"
    ,catalog="doanspring"
)
public class Chitietdonhang  implements java.io.Serializable {


     private Integer id;
     private Donhang donhang;
     private Sanpham sanpham;
     private Integer soluongdathang;
     private Long dongia;
     private Date ngaytao;

    public Chitietdonhang() {
    }

    public Chitietdonhang(Donhang donhang, Sanpham sanpham, Integer soluongdathang, Long dongia, Date ngaytao) {
       this.donhang = donhang;
       this.sanpham = sanpham;
       this.soluongdathang = soluongdathang;
       this.dongia = dongia;
       this.ngaytao = ngaytao;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="donhang_id")
    public Donhang getDonhang() {
        return this.donhang;
    }
    
    public void setDonhang(Donhang donhang) {
        this.donhang = donhang;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sanpham_id")
    public Sanpham getSanpham() {
        return this.sanpham;
    }
    
    public void setSanpham(Sanpham sanpham) {
        this.sanpham = sanpham;
    }

    
    @Column(name="soluongdathang")
    public Integer getSoluongdathang() {
        return this.soluongdathang;
    }
    
    public void setSoluongdathang(Integer soluongdathang) {
        this.soluongdathang = soluongdathang;
    }

    
    @Column(name="dongia", precision=10, scale=0)
    public Long getDongia() {
        return this.dongia;
    }
    
    public void setDongia(Long dongia) {
        this.dongia = dongia;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ngaytao", length=19)
    public Date getNgaytao() {
        return this.ngaytao;
    }
    
    public void setNgaytao(Date ngaytao) {
        this.ngaytao = ngaytao;
    }




}


