package entity;
// Generated Jan 10, 2017 7:57:48 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Giohang generated by hbm2java
 */
@Entity
@Table(name="giohang"
    ,catalog="doanspring"
)
public class Giohang  implements java.io.Serializable {


     private Integer id;
     private Khachhang khachhang;
     private Sanpham sanpham;
     private String dongia;
     private Integer soluong;
     private Date ngaytao;

    public Giohang() {
    }

    public Giohang(Khachhang khachhang, Sanpham sanpham, String dongia, Integer soluong, Date ngaytao) {
       this.khachhang = khachhang;
       this.sanpham = sanpham;
       this.dongia = dongia;
       this.soluong = soluong;
       this.ngaytao = ngaytao;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="khachhang_id")
    public Khachhang getKhachhang() {
        return this.khachhang;
    }
    
    public void setKhachhang(Khachhang khachhang) {
        this.khachhang = khachhang;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sanpham_id")
    public Sanpham getSanpham() {
        return this.sanpham;
    }
    
    public void setSanpham(Sanpham sanpham) {
        this.sanpham = sanpham;
    }

    
    @Column(name="dongia", length=50)
    public String getDongia() {
        return this.dongia;
    }
    
    public void setDongia(String dongia) {
        this.dongia = dongia;
    }

    
    @Column(name="soluong")
    public Integer getSoluong() {
        return this.soluong;
    }
    
    public void setSoluong(Integer soluong) {
        this.soluong = soluong;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ngaytao", length=10)
    public Date getNgaytao() {
        return this.ngaytao;
    }
    
    public void setNgaytao(Date ngaytao) {
        this.ngaytao = ngaytao;
    }




}


