package entity;
// Generated Jan 10, 2017 7:57:48 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * Hoadon generated by hbm2java
 */
@Entity
@Table(name="hoadon"
    ,catalog="doanspring"
)
public class Hoadon  implements java.io.Serializable {


     private Integer id;
     private Donhang donhang;
     private Nhanvien nhanvien;
     private Integer sosp;
     private String tongtien;
     private String sodienthoai;
     private Date ngaygiaohang;
     private String diachigiaohang;
     private Integer trangthai;
     private String ghichu;
     private Date ngaytao;

    public Hoadon() {
    }

    public Hoadon(Donhang donhang, Nhanvien nhanvien, Integer sosp, String tongtien, String sodienthoai, Date ngaygiaohang, String diachigiaohang, Integer trangthai, String ghichu, Date ngaytao) {
       this.donhang = donhang;
       this.nhanvien = nhanvien;
       this.sosp = sosp;
       this.tongtien = tongtien;
       this.sodienthoai = sodienthoai;
       this.ngaygiaohang = ngaygiaohang;
       this.diachigiaohang = diachigiaohang;
       this.trangthai = trangthai;
       this.ghichu = ghichu;
       this.ngaytao = ngaytao;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="donhang_id")
    public Donhang getDonhang() {
        return this.donhang;
    }
    
    public void setDonhang(Donhang donhang) {
        this.donhang = donhang;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="nhanvien_id")
    public Nhanvien getNhanvien() {
        return this.nhanvien;
    }
    
    public void setNhanvien(Nhanvien nhanvien) {
        this.nhanvien = nhanvien;
    }

    
    @Column(name="sosp")
    public Integer getSosp() {
        return this.sosp;
    }
    
    public void setSosp(Integer sosp) {
        this.sosp = sosp;
    }

    
    @Column(name="tongtien", length=50)
    public String getTongtien() {
        return this.tongtien;
    }
    
    public void setTongtien(String tongtien) {
        this.tongtien = tongtien;
    }

    
    @Column(name="sodienthoai", length=250)
    public String getSodienthoai() {
        return this.sodienthoai;
    }
    
    public void setSodienthoai(String sodienthoai) {
        this.sodienthoai = sodienthoai;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ngaygiaohang", length=19)
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    public Date getNgaygiaohang() {
        return this.ngaygiaohang;
    }
    
    public void setNgaygiaohang(Date ngaygiaohang) {
        this.ngaygiaohang = ngaygiaohang;
    }

    
    @Column(name="diachigiaohang", length=250)
    public String getDiachigiaohang() {
        return this.diachigiaohang;
    }
    
    public void setDiachigiaohang(String diachigiaohang) {
        this.diachigiaohang = diachigiaohang;
    }

    
    @Column(name="trangthai")
    public Integer getTrangthai() {
        return this.trangthai;
    }
    
    public void setTrangthai(Integer trangthai) {
        this.trangthai = trangthai;
    }

    
    @Column(name="ghichu", length=65535)
    public String getGhichu() {
        return this.ghichu;
    }
    
    public void setGhichu(String ghichu) {
        this.ghichu = ghichu;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ngaytao", length=10)
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    public Date getNgaytao() {
        return this.ngaytao;
    }
    
    public void setNgaytao(Date ngaytao) {
        this.ngaytao = ngaytao;
    }




}


