package entity;
// Generated Dec 27, 2016 10:57:08 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Loaida generated by hbm2java
 */
@Entity
@Table(name="loaida"
    ,catalog="doanspring"
)
public class Loaida  implements java.io.Serializable {


     private Integer id;
     private String ten;
     private String ma;
     private String mota;
     private Integer daxoa;
     private String hinhdang;
     private Long kichthuoc;
     private String chatluong;
     private Date ngaytao;
     private Set<Sanpham> sanphams = new HashSet<Sanpham>(0);

    public Loaida() {
    }

    public Loaida(String ten, String ma, String mota, Integer daxoa, String hinhdang, Long kichthuoc, String chatluong, Date ngaytao, Set<Sanpham> sanphams) {
       this.ten = ten;
       this.ma = ma;
       this.mota = mota;
       this.daxoa = daxoa;
       this.hinhdang = hinhdang;
       this.kichthuoc = kichthuoc;
       this.chatluong = chatluong;
       this.ngaytao = ngaytao;
       this.sanphams = sanphams;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="ten", length=250)
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }

    
    @Column(name="ma", length=50)
    public String getMa() {
        return this.ma;
    }
    
    public void setMa(String ma) {
        this.ma = ma;
    }

    
    @Column(name="mota", length=65535)
    public String getMota() {
        return this.mota;
    }
    
    public void setMota(String mota) {
        this.mota = mota;
    }

    
    @Column(name="daxoa")
    public Integer getDaxoa() {
        return this.daxoa;
    }
    
    public void setDaxoa(Integer daxoa) {
        this.daxoa = daxoa;
    }

    
    @Column(name="hinhdang", length=250)
    public String getHinhdang() {
        return this.hinhdang;
    }
    
    public void setHinhdang(String hinhdang) {
        this.hinhdang = hinhdang;
    }

    
    @Column(name="kichthuoc", precision=10, scale=0)
    public Long getKichthuoc() {
        return this.kichthuoc;
    }
    
    public void setKichthuoc(Long kichthuoc) {
        this.kichthuoc = kichthuoc;
    }

    
    @Column(name="chatluong", length=50)
    public String getChatluong() {
        return this.chatluong;
    }
    
    public void setChatluong(String chatluong) {
        this.chatluong = chatluong;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ngaytao", length=19)
    public Date getNgaytao() {
        return this.ngaytao;
    }
    
    public void setNgaytao(Date ngaytao) {
        this.ngaytao = ngaytao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="loaida")
    public Set<Sanpham> getSanphams() {
        return this.sanphams;
    }
    
    public void setSanphams(Set<Sanpham> sanphams) {
        this.sanphams = sanphams;
    }




}


