package entity;
// Generated Jan 4, 2017 2:03:24 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Nhanvien generated by hbm2java
 */
@Entity
@Table(name="nhanvien"
    ,catalog="doanspring"
)
public class Nhanvien  implements java.io.Serializable {


     private Integer id;
     private Chucvu chucvu;
     private String ten;
     private String ma;
     private Date ngaysinh;
     private String gioitinh;
     private String diachi;
     private String sodienthoai;
     private String tendangnhap;
     private String matkhau;
     private Set<Hoadon> hoadons = new HashSet<Hoadon>(0);
     private Set<Khohang> khohangs = new HashSet<Khohang>(0);

    public Nhanvien() {
    }

    public Nhanvien(Chucvu chucvu, String ten, String ma, Date ngaysinh, String gioitinh, String diachi, String sodienthoai, String tendangnhap, String matkhau, Set<Hoadon> hoadons, Set<Khohang> khohangs) {
       this.chucvu = chucvu;
       this.ten = ten;
       this.ma = ma;
       this.ngaysinh = ngaysinh;
       this.gioitinh = gioitinh;
       this.diachi = diachi;
       this.sodienthoai = sodienthoai;
       this.tendangnhap = tendangnhap;
       this.matkhau = matkhau;
       this.hoadons = hoadons;
       this.khohangs = khohangs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="chucvu_id")
    public Chucvu getChucvu() {
        return this.chucvu;
    }
    
    public void setChucvu(Chucvu chucvu) {
        this.chucvu = chucvu;
    }

    
    @Column(name="ten", length=250)
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }

    
    @Column(name="ma", length=50)
    public String getMa() {
        return this.ma;
    }
    
    public void setMa(String ma) {
        this.ma = ma;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ngaysinh", length=10)
    public Date getNgaysinh() {
        return this.ngaysinh;
    }
    
    public void setNgaysinh(Date ngaysinh) {
        this.ngaysinh = ngaysinh;
    }

    
    @Column(name="gioitinh", length=10)
    public String getGioitinh() {
        return this.gioitinh;
    }
    
    public void setGioitinh(String gioitinh) {
        this.gioitinh = gioitinh;
    }

    
    @Column(name="diachi", length=250)
    public String getDiachi() {
        return this.diachi;
    }
    
    public void setDiachi(String diachi) {
        this.diachi = diachi;
    }

    
    @Column(name="sodienthoai", length=250)
    public String getSodienthoai() {
        return this.sodienthoai;
    }
    
    public void setSodienthoai(String sodienthoai) {
        this.sodienthoai = sodienthoai;
    }

    
    @Column(name="tendangnhap", length=250)
    public String getTendangnhap() {
        return this.tendangnhap;
    }
    
    public void setTendangnhap(String tendangnhap) {
        this.tendangnhap = tendangnhap;
    }

    
    @Column(name="matkhau", length=250)
    public String getMatkhau() {
        return this.matkhau;
    }
    
    public void setMatkhau(String matkhau) {
        this.matkhau = matkhau;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nhanvien")
    public Set<Hoadon> getHoadons() {
        return this.hoadons;
    }
    
    public void setHoadons(Set<Hoadon> hoadons) {
        this.hoadons = hoadons;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nhanvien")
    public Set<Khohang> getKhohangs() {
        return this.khohangs;
    }
    
    public void setKhohangs(Set<Khohang> khohangs) {
        this.khohangs = khohangs;
    }




}


